### ISSUE TITLE
command line tools for X2K not working.

### ISSUE THREAD

**Issue by harshitmanek** [MaayanLab/x2k_web#12]
I tried using the command line standalone versions of the X2K tools in JAR format. It isn't working. I am getting errors on running it. Could you please check. If it is fine, please share a bit detailed instruction around using the command line tool.

**Comment by maxim-k** [comment]
What format did you use for 'genelist'? It was unclear from the webpage (we just fixed it), that it should be a text file with a list of genes separated by newlines.
You can find more detailed [manual](http://www.maayanlab.net/X2K/documentation.html) on the [original X2K page](http://www.maayanlab.net/X2K/). But we don't maintain standalone version now.
