### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by zhernovkov** [MaayanLab/x2k_web#15]
Hello! I tried to use the X2K API, but I got an error: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Could you help me with this issue? 

---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-16-a67c220b2ab5> in <module>
----> 1 x2k_results = run_X2K(input_genes)

<ipython-input-14-fb3733ff0730> in run_X2K(input_genes, options)
     58 
     59     # Convert to dictionary
---> 60     x2k_results = {key: json.loads(value) if key != 'input' else value for key, value in json.loads(data).items()}
     61 
     62     # Clean results

~\anaconda3\lib\json\__init__.py in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    355             parse_int is None and parse_float is None and
    356             parse_constant is None and object_pairs_hook is None and not kw):
--> 357         return _default_decoder.decode(s)
    358     if cls is None:
    359         cls = JSONDecoder

~\anaconda3\lib\json\decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

~\anaconda3\lib\json\decoder.py in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by u8sand** [comment]
We'll need to update the example notebook, but for now, you can use the following function instead of the one shown:

```python
import requests

def run_X2K(input_genes, options={}):
  body = {
    'text-genes': '\n'.join(input_genes),
    'included_organisms': 'both',
    'TF-target gene background database used for enrichment': 'ChEA & ENCODE Consensus',
    'sort transcription factors by': 'p-value',
    'min_network_size': 10,
    'number of top TFs': 10,
    'path_length': 2,
    'min_number_of_articles_supporting_interaction': 0,
    'max_number_of_interactions_per_protein': 200,
    'max_number_of_interactions_per_article': 100,
    'enable_BioGRID': True,
    'enable_IntAct': True,
    'enable_MINT': True,
    'enable_ppid': True,
    'enable_Stelzl': True,
    'kinase interactions to include': 'kea 2018',
    'sort kinases by': 'p-value'
  }
  # override defaults
  body.update(options)
  # submit post
  response = requests.post(
    'https://maayanlab.cloud/X2K/api',
    files=[(k, (None, v)) for k, v in body.items()],
  )
  return response.json()
```

The primary issue is that we move the application to a different host `maayanlab.cloud` from `amp.pharm.mssm.edu` and unfortunately the implementation here doesn't seem to follow the redirect. The above version which uses the `requests` module should be more resilient to this and also clearer to show how it works.

Let us know if you have issues with using the API with this alternative function.

**Comment by zhernovkov** [comment]
Thanks, now it works.

but I got another error when I run 
import pandas as pd
chea_dataframe = pd.DataFrame(x2k_results['ChEA'])

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-34-81200653f27e> in <module>
      1 # KEA Results
----> 2 kea_dataframe = pd.DataFrame(x2k_results['KEA'])
      3 kea_dataframe.head()

~\anaconda3\lib\site-packages\pandas\core\frame.py in __init__(self, data, index, columns, dtype, copy)
    527         else:
    528             if index is None or columns is None:
--> 529                 raise ValueError("DataFrame constructor not properly called!")
    530 
    531             if not dtype:

ValueError: DataFrame constructor not properly called!

**Comment by u8sand** [comment]
@zhernovkov I suppose this logic was likely in the original query; we'll try and update it next week. But now that you have the `x2k_results` you can inspect it and determine how to proceed.

To load the KEA it's something like
```python
import json

kea_results = json.loads(x2k_results['KEA'])
kea_dataframe = pd.DataFrame(kea_results['kinases'])
```

The others will be similar though not identical.

**Comment by zhernovkov** [comment]
Thanks!
is it possible to use the API in R?

**Comment by u8sand** [comment]
Yes; any language can access this, but it'll be up to you to figure out the specifics. It is a REST API and the request is a `multi-part form-data POST request` with the variables seen in the python code. In R, httr should be able to construct such a request.
