### ISSUE TITLE
Submit button looks purple on my screen

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/x2k_web#4]
@u8sand @maxim-k the Submit buttons (the main one and the one under LJP) are not in the same color blue like the rest of the hyperlinked text on the site... Can you please fix it?

**Comment by u8sand** [comment]
This is very weird because on no other system that I try does it look
purple... Will investigate though I may want to look at it on your computer.

**Comment by AviMaayan** [comment]
Not critical.


Best,


Avi


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Avi Ma’ayan, PhD
Professor, Department of Pharmacological Sciences
Director, Mount Sinai Center for Bioinformatics
Icahn School of Medicine at Mount Sinai
New York, NY 10029
(212) 241-1153
Lab: http://www.mssm.edu/labs/maayan
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
________________________________
